---
name: pre-commit

on:
  pull_request:
    branches:
      - 'master'

jobs:
  pre-commit:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Oracle Cloud Infrastructure CLI
        run: |
          mkdir -p /home/runner/.oci/
          echo "${{ secrets.OCI_API_KEY }}" > /home/runner/.oci/oci_api_key.pem
          echo "${{ secrets.OCI_CONFIG }}" > /home/runner/.oci/config
          chmod 600 /home/runner/.oci/oci_api_key.pem
          chmod 600 /home/runner/.oci/config

      - name: Checkout
        uses: actions/checkout@v6

      - name: Install Terraform
        uses: hashicorp/setup-terraform@v4

      - name: Install Python
        uses: actions/setup-python@v6
        with:
          python-version: '3.13'

      - name: Install prerequisites (terraform-docs, tflint)
        run: |
          # Install terraform-docs
          sudo wget -q -O /usr/local/bin/terraform-docs.tar.gz $(curl -sL https://api.github.com/repos/terraform-docs/terraform-docs/releases/latest | grep browser_download_url | grep -o -E "https://.+?-linux-amd64.tar.gz")
          sudo tar -xzf /usr/local/bin/terraform-docs.tar.gz -C /usr/local/bin
          sudo chmod +x /usr/local/bin/terraform-docs

          # Install tflint
          sudo wget -q -O /tmp/tflint.zip $(curl -sL https://api.github.com/repos/terraform-linters/tflint/releases/latest | grep browser_download_url | grep -o -E "https://.+?_linux_amd64.zip")
          sudo unzip -o /tmp/tflint.zip -d /usr/local/bin
          sudo chmod +x /usr/local/bin/tflint

      - name: Run pre-commit action
        uses: pre-commit/action@v3.0.1
