---
name: Terraform Module Releaser

on:
  pull_request:
    types:
      - opened
      - reopened
      - synchronize
      - closed
    branches:
      - master
    paths:
      - 'oci/**'

permissions:
  contents: write
  pull-requests: write

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v6

      - name: Terraform Module Releaser
        uses: techpivot/terraform-module-releaser@v2
        with:
          module-path-ignore: "**/examples/**"
